services:
  chart-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: chart-saha-airlines:latest
    container_name: chart-saha-airlines
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - saha-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chart_http.rule=Host(`chart.sahaair.com`, `www.chart.sahaair.com`)"
      - "traefik.http.routers.chart_http.entrypoints=web"
      - "traefik.http.routers.chart_http.middlewares=redirect-to-https@file,www-to-non-www@file"
      - "traefik.http.routers.chart_https.rule=Host(`chart.sahaair.com`, `www.chart.sahaair.com`)"
      - "traefik.http.routers.chart_https.entrypoints=websecure"
      - "traefik.http.routers.chart_https.middlewares=www-to-non-www@file"
      - "traefik.http.routers.chart_https.tls=true"
      - "traefik.http.services.chart.loadbalancer.server.port=80"
    # برای تست لوکال بدون Traefik باز کن:
    # ports:
    #   - "8080:80"

networks:
  saha-network:
    external: true
