services:
  chart-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: chart-saha-airlines:latest
    container_name: chart-saha-airlines
    restart: unless-stopped
    networks:
      - saha-network
    depends_on:
      - chart-api
    environment:
      - API_BASE_URL=http://chart-api:3001
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.chart_http.rule=Host(`chart.sahaair.com`) || Host(`www.chart.sahaair.com`)"
      - "traefik.http.routers.chart_http.entrypoints=web"
      - "traefik.http.routers.chart_http.middlewares=redirect-to-https@file,www-to-non-www@file"

      - "traefik.http.routers.chart_https.rule=Host(`chart.sahaair.com`) || Host(`www.chart.sahaair.com`)"
      - "traefik.http.routers.chart_https.entrypoints=websecure"
      - "traefik.http.routers.chart_https.middlewares=www-to-non-www@file"

      - "traefik.http.routers.chart_https.tls=true"
      - "traefik.http.services.chart.loadbalancer.server.port=80"

  chart-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: chart-saha-airlines-api:latest
    container_name: chart-saha-airlines-api
    restart: unless-stopped
    networks:
      - saha-network
    volumes:
      - ./public:/app/public
    expose:
      - "3001"

networks:
  saha-network:
    external: true
