services:
  web:
    build: .
    image: chart-saha-airlines:latest
    container_name: chart-saha-airlines
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chart_http.rule=Host(`chart.sahaair.com`) || Host(`www.chart.sahaair.com`)"
      - "traefik.http.routers.chart_http.entrypoints=web"
      - "traefik.http.routers.chart_http.middlewares=redirect-to-https@file,www-to-non-www@file"
      - "traefik.http.routers.chart_https.rule=Host(`chart.sahaair.com`) || Host(`www.chart.sahaair.com`)"
      - "traefik.http.routers.chart_https.entrypoints=websecure"
      - "traefik.http.routers.chart_https.middlewares=www-to-non-www@file"
      - "traefik.http.routers.chart_https.tls=true"
      - "traefik.http.services.chart.loadbalancer.server.port=80"
    networks:
      - saha-network

networks:
  saha-network:
    external: true